config/routes.rb
Rails.application.routes.draw do
 
  get 'editorder/:id/showinvited/' => 'editorder#showinvited'

  get 'editorder/:id/showjoined/'  => 'editorder#showjoined'

  get 'editorder/:id/remove/'       => 'editorder#remove'
  get 'editorder/:id/getuser/'       => 'editorder#getuser'
  

  resources :ordetails

  resources :usgroups

  resources :friendships

  resources :groups

  resources :orders

  resources :inviteds

  resources :friendships

  root 'welcome#index'
  

  devise_for :users, :controllers => { registrations: 'registrations' , :omniauth_callbacks => "callbacks" }

  
    get 'orders/joined/all' => 'orders#joined'

    get 'notifications/show' => 'notifications#show'

    resources :users do
    resources :orders
  end
   resources :users do
    resources :groups
  end

   resources :users do
    resources :inviteds
  end

   resources :orders do
       resources :inviteds
    end

  resources :users do
       resources :friendships
    end

  resources :users do
       resources :usgroups
  end
      
  resources :groups do
       resources :usgroups
  end

  resources :users do
    resources :ordetails
  end

   resources :orders do
       resources :ordetails
    end

resources :notifications do
  collection do
    post :mark_as_read
  end

  end

resources :ordetails do
  collection do
    post :join
  end

  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
 
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.where(user_id: current_user.id)
    #@friendships = Friendship.all
    @friendship = Friendship.new
    @users = User.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    #@friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @usersByEmail = User.find_by(email: friendship_params[:friend_id]) 

    if @usersByEmail

      if @usersByEmail.id == current_user.id || Friendship.find_by(user_id: friendship_params[:user_id], friend_id: @usersByEmail.id )
        
        respond_to do |format|
            format.html { redirect_to friendships_url, notice: 'Friendship was Not created.' }
        end

      else
        @friendship = Friendship.new(friend_id: @usersByEmail.id, user_id: friendship_params[:user_id])
        respond_to do |format|
          if @friendship.save
            format.html { redirect_to friendships_url, notice: 'Friendship was successfully created.' }
            #format.json { render :index, status: :created, location: @friendship }
          else
            format.html { render :index }
            format.json { render json: @friendship.errors, status: :unprocessable_entity }
          end
        end
        
      end
    else
      respond_to do |format|
            format.html { redirect_to friendships_url, notice: 'Email Not Found or not Correct.' }
            format.json { render json: @friendship.errors, status: :unprocessable_entity }
        end
    end

    
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    # @friendshipId = Friendship.find_by(id: params[:id], user_id: current_user.id)

    #  @groupFriend = Group.where(user_id: current_user.id)

    #   @groupFriend.each do |gf|
    #      @userGroup = Usgroup.find_by(group_id: gf.id, user_id: @friendshipId.friend_id)
       
    #      @removeFriendGroup = Usgroup.destroy(id: @userGroup.id)
    #    end

    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:friend_id, :user_id)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-12">

    <div class="field col-sm-4">
      <div class="col-sm-2">
        <%= f.label :friend_id %>
      </div>
      <div class="col-sm-2">
        <%= f.text_field :friend_id , :list=>"email" , :required => true %>
      </div>
    </div>

    <datalist id="email">
      <% (@users-[current_user]).each do |u| %>
        <option value="<%= u.email %>"><%= u.email %></option>
      <% end %>
    </datalist>

    <div class="field">
      <%= f.hidden_field :user_id , :value=>current_user.id %>
    </div>

    <div class="actions col-sm-4">
      <%= f.submit :value=>"Add" , :id=>"submit" , :class=> 'btn btn-primary' %>
    </div>

  </div>

<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friends</h1>

<!-- <%= link_to 'New Friendship', new_friendship_path %>-->

<%= render 'form' %>


<fieldset class="scroll col-sm-12">
  <legend>Friends List:</legend>
  <% @friendships.each do |friendship| %>
    <div class="col-sm-4">
      <img class="col-sm-5" src="<%= friendship.friend.avatar %>">
      <div class="col-sm-6">
        <span class="col-sm-12"><%= friendship.friend.name %></span>
        <span class="col-sm-12"><%= link_to 'Unfriend', friendship, method: :delete, data: { confirm: 'Are you sure?' }, :class=> 'btn btn-danger' %></span>
      </div>
    </div>
  <% end %>
</fieldset>
    

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>