config/routes.rb
Rails.application.routes.draw do
 
  get 'editorder/:id/showinvited/' => 'editorder#showinvited'

  get 'editorder/:id/showjoined/'  => 'editorder#showjoined'

  get 'editorder/:id/remove/'       => 'editorder#remove'
  get 'editorder/:id/getuser/'       => 'editorder#getuser'
  

  resources :ordetails

  resources :usgroups

  resources :friendships

  resources :groups

  resources :orders

  resources :inviteds

  resources :friendships

  root 'welcome#index'
  

  devise_for :users, :controllers => { registrations: 'registrations' , :omniauth_callbacks => "callbacks" }

  
    get 'orders/joined/all' => 'orders#joined'

    get 'notifications/show' => 'notifications#show'

    resources :users do
    resources :orders
  end
   resources :users do
    resources :groups
  end

   resources :users do
    resources :inviteds
  end

   resources :orders do
       resources :inviteds
    end

  resources :users do
       resources :friendships
    end

  resources :users do
       resources :usgroups
  end
      
  resources :groups do
       resources :usgroups
  end

  resources :users do
    resources :ordetails
  end

   resources :orders do
       resources :ordetails
    end

resources :notifications do
  collection do
    post :mark_as_read
  end

  end

resources :ordetails do
  collection do
    post :join
  end

  end

end

app/models/usgroup.rb
class Usgroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/usgroups_controller.rb
class UsgroupsController < ApplicationController
  before_action :set_usgroup, only: [:show, :edit, :update, :destroy]

  # GET /usgroups
  # GET /usgroups.json
  def index
    @usgroups = Usgroup.all
  end

  # GET /usgroups/1
  # GET /usgroups/1.json
  def show
  end

  # GET /usgroups/new
  def new
    @usgroup = Usgroup.new
  end

  # GET /usgroups/1/edit
  def edit
  end

  # POST /usgroups
  # POST /usgroups.json
  def create
    @usersByName = User.find_by(name: usgroup_params[:user_id])

    if @usersByName && Friendship.find_by(user_id: current_user.id, friend_id: @usersByName.id )

      if @usersByName.id == current_user.id || Usgroup.find_by(user_id: @usersByName.id , group_id: usgroup_params[:group_id])

        respond_to do |format|
            format.html { redirect_to groups_url, notice: 'User was Not added.' }
        end

      else

        @usgroup = Usgroup.new(user_id: @usersByName.id , group_id: usgroup_params[:group_id])

        # respond_to do |format|
          if @usgroup.save
            redirect_to "/groups/"+usgroup_params[:group_id]+""
            # format.html { redirect_to groups_url ,notice: 'Usgroup was successfully created.' }
           # format.json { render :show, status: :created, location: @usgroup }
          else
            # format.html { render :new }
            # format.json { render json: @usgroup.errors, status: :unprocessable_entity }
          end
        # end

      end


    else
      respond_to do |format|
        format.html { redirect_to groups_url , notice: 'Name does not exist or not one of your friends.' }
        format.json { render json: @usgroup.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /usgroups/1
  # PATCH/PUT /usgroups/1.json
  def update
    respond_to do |format|
      if @usgroup.update(usgroup_params)
        format.html { redirect_to @usgroup, notice: 'Usgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @usgroup }
      else
        format.html { render :edit }
        format.json { render json: @usgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usgroups/1
  # DELETE /usgroups/1.json
  def destroy
    @grId = @usgroup.group_id.to_s
    
    @usgroup.destroy
     redirect_to "/groups/"+@grId+""
    # respond_to do |format|
    #   format.html { redirect_to groups_url, notice: 'Usgroup was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usgroup
      @usgroup = Usgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usgroup_params
      params.require(:usgroup).permit(:user_id, :group_id)
    end
end
 

app/helpers/usgroups_helper.rb
module UsgroupsHelper
end

app/views/usgroups/_form.html.erb
<%= form_for(@usgroup) do |f| %>
  <% if @usgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usgroup.errors.count, "error") %> prohibited this usgroup from being saved:</h2>

      <ul>
      <% @usgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.number_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usgroups/edit.html.erb
<h1>Editing Usgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @usgroup %> |
<%= link_to 'Back', usgroups_path %>

app/views/usgroups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usgroups</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usgroups.each do |usgroup| %>
      <tr>
        <td><%= usgroup.user_id %></td>
        <td><%= usgroup.group_id %></td>
        <td><%= link_to 'Show', usgroup %></td>
        <td><%= link_to 'Edit', edit_usgroup_path(usgroup) %></td>
        <td><%= link_to 'Destroy', usgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usgroup', new_usgroup_path %>

app/views/usgroups/new.html.erb
<h1>New Usgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', usgroups_path %>

app/views/usgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @usgroup.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @usgroup.group_id %>
</p>

<%= link_to 'Edit', edit_usgroup_path(@usgroup) %> |
<%= link_to 'Back', usgroups_path %>