config/routes.rb
Rails.application.routes.draw do
 
  get 'editorder/:id/showinvited/' => 'editorder#showinvited'

  get 'editorder/:id/showjoined/'  => 'editorder#showjoined'

  get 'editorder/:id/remove/'       => 'editorder#remove'
  get 'editorder/:id/getuser/'       => 'editorder#getuser'
  

  resources :ordetails

  resources :usgroups

  resources :friendships

  resources :groups

  resources :orders

  resources :inviteds

  resources :friendships

  root 'welcome#index'
  

  devise_for :users, :controllers => { registrations: 'registrations' , :omniauth_callbacks => "callbacks" }

  
    get 'orders/joined/all' => 'orders#joined'

    get 'notifications/show' => 'notifications#show'

    resources :users do
    resources :orders
  end
   resources :users do
    resources :groups
  end

   resources :users do
    resources :inviteds
  end

   resources :orders do
       resources :inviteds
    end

  resources :users do
       resources :friendships
    end

  resources :users do
       resources :usgroups
  end
      
  resources :groups do
       resources :usgroups
  end

  resources :users do
    resources :ordetails
  end

   resources :orders do
       resources :ordetails
    end

resources :notifications do
  collection do
    post :mark_as_read
  end

  end

resources :ordetails do
  collection do
    post :join
  end

  end

end

app/models/invited.rb
class Invited < ActiveRecord::Base
	
end

app/controllers/inviteds_controller.rb
class InvitedsController < ApplicationController
  before_action :set_invited, only: [:show, :edit, :update, :destroy]

  # GET /inviteds
  # GET /inviteds.json
  def index
      redirect_to '/'
  end

  # GET /inviteds/1
  # GET /inviteds/1.json
  def show
      redirect_to '/'
  end

  # GET /inviteds/new
  def new
   redirect_to '/'
  end

  # GET /inviteds/1/edit
  def edit
  end

  # POST /inviteds
  # POST /inviteds.json
  def create
    @invited = Invited.new(invited_params)

    respond_to do |format|
      if @invited.save
        format.html { redirect_to @invited, notice: 'Invited was successfully created.' }
        format.json { render :show, status: :created, location: @invited }
      else
        format.html { render :new }
        format.json { render json: @invited.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inviteds/1
  # PATCH/PUT /inviteds/1.json
  def update
    respond_to do |format|
      if @invited.update(invited_params)
        format.html { redirect_to @invited, notice: 'Invited was successfully updated.' }
        format.json { render :show, status: :ok, location: @invited }
      else
        format.html { render :edit }
        format.json { render json: @invited.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inviteds/1
  # DELETE /inviteds/1.json
  def destroy
    @invited.destroy
    respond_to do |format|
      format.html { redirect_to inviteds_url, notice: 'Invited was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invited
      @invited = Invited.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invited_params
      params.require(:invited).permit(:user_id, :order_id)
    end
end

app/helpers/inviteds_helper.rb
module InvitedsHelper
end

app/views/inviteds/_form.html.erb
<%= form_for(@invited) do |f| %>
  <% if @invited.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invited.errors.count, "error") %> prohibited this invited from being saved:</h2>

      <ul>
      <% @invited.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inviteds/edit.html.erb
<h1>Editing Invited</h1>

<%= render 'form' %>

<%= link_to 'Show', @invited %> |
<%= link_to 'Back', inviteds_path %>

app/views/inviteds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inviteds</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inviteds.each do |invited| %>
      <tr>
        <td><%= invited.user_id %></td>
        <td><%= invited.order_id %></td>
        <td><%= link_to 'Show', invited %></td>
        <td><%= link_to 'Edit', edit_invited_path(invited) %></td>
        <td><%= link_to 'Destroy', invited, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invited', new_invited_path %>

app/views/inviteds/new.html.erb
<h1>New Invited</h1>

<%= render 'form' %>

<%= link_to 'Back', inviteds_path %>

app/views/inviteds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @invited.user_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @invited.order_id %>
</p>

<%= link_to 'Edit', edit_invited_path(@invited) %> |
<%= link_to 'Back', inviteds_path %>