config/routes.rb
Rails.application.routes.draw do
 
  get 'editorder/:id/showinvited/' => 'editorder#showinvited'

  get 'editorder/:id/showjoined/'  => 'editorder#showjoined'

  get 'editorder/:id/remove/'       => 'editorder#remove'
  get 'editorder/:id/getuser/'       => 'editorder#getuser'
  

  resources :ordetails

  resources :usgroups

  resources :friendships

  resources :groups

  resources :orders

  resources :inviteds

  resources :friendships

  root 'welcome#index'
  

  devise_for :users, :controllers => { registrations: 'registrations' , :omniauth_callbacks => "callbacks" }

  
    get 'orders/joined/all' => 'orders#joined'

    get 'notifications/show' => 'notifications#show'

    resources :users do
    resources :orders
  end
   resources :users do
    resources :groups
  end

   resources :users do
    resources :inviteds
  end

   resources :orders do
       resources :inviteds
    end

  resources :users do
       resources :friendships
    end

  resources :users do
       resources :usgroups
  end
      
  resources :groups do
       resources :usgroups
  end

  resources :users do
    resources :ordetails
  end

   resources :orders do
       resources :ordetails
    end

resources :notifications do
  collection do
    post :mark_as_read
  end

  end

resources :ordetails do
  collection do
    post :join
  end

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AtlobApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css" />

    <!--external css-->
    <!-- font icon -->
    <link href="/template/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="/template/css/font-awesome.min.css" rel="stylesheet" />    
    <!-- full calendar css-->
    <link href="/template/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <link href="/template/assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href="/template/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>
    <!-- owl carousel -->
    <link rel="stylesheet" href="/template/css/owl.carousel.css" type="text/css">
  <link href="/template/css/jquery-jvectormap-1.2.2.css" rel="stylesheet">
    <!-- Custom styles -->
  <link rel="stylesheet" href="/template/css/fullcalendar.css">
  <link href="/template/css/widgets.css" rel="stylesheet">
    <link href="/template/css/style.css" rel="stylesheet">
    <link href="/template/css/style-responsive.css" rel="stylesheet" />
  <link href="/template/css/xcharts.min.css" rel=" stylesheet"> 
  <link href="/template/css/jquery-ui-1.10.4.min.css" rel="stylesheet">

  <style>
    .ui-state-default{
      border-radius: 0px !important;
    }
  </style>

</head>

<body id="top" onload="prettyPrint();">

  <section id="container" class="">
   
    <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
            </div>

            <!--logo start-->
            <a href="/" class="logo">Yalla <span class="lite">Notlob</span></a>
            <!--logo end-->



           

            <div class="top-nav notification-row">                
              <!-- notificatoin dropdown start-->
              <%if user_signed_in? %>


            


              <ul class="nav pull-right top-menu">

                <!-- alert notification start-->
                <li id="alert_notificatoin_bar" class="dropdown" data-behavior="notifications">


                  <a data-toggle="dropdown" class="dropdown-toggle" data-behavior="notifications-link" href="#">

                    <i class="icon-bell-l"></i>
                    <span class="badge bg-important" data-behavior="unread-count"></span>
                  </a>
                  <ul class="dropdown-menu extended notification" id="notify" data-behavior="notification-items">
                    <div class="notify-arrow notify-arrow-blue"></div>
                 <!--    <li>
                      <p class="blue">You have 4 new notifications</p>
                    </li> -->
 
                    
                      <a href="#">See all notifications</a>
                    </li>
                  </ul>


                </li>
                <!-- alert notification end-->
                <!-- user login dropdown start-->

                <li class="dropdown <%= params[:controller]== 'users' ? 'active' : '' %>">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="profile-ava">
                      <img class="img-circle" alt="no image" width="35" height="35" src="<%= current_user.avatar %>" />
                    </span>
                    <span class="username"><%= current_user.name %></span>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu extended logout">
                    <div class="log-arrow-up"></div>
                    <li class="eborder-top">
                      <a href="<%= user_path(current_user) %>">
                        <i class="icon_profile"></i> My Profile
                      </a>
                    </li>
                    <li class="eborder-top" style="text-align:center;">
                      <%= link_to 'Log Out', destroy_user_session_path ,method: :delete %>
                    </li>

                  </ul>
                </li>
                 <% end %> 
                <!-- user login dropdown end -->
              </ul>
              <!-- notificatoin dropdown end-->
            </div>
    </header>

    <!--sidebar start-->
    <aside>
      <div id="sidebar"  class="nav-collapse ">

        <!-- sidebar menu start-->
        <ul class="sidebar-menu"> 
          <%if user_signed_in? %>

          <li onClick='refhome()'  class="<%= params[:controller]== 'welcome' ? 'active' : '' %>">
            <a class="" href="<%=root_path%>">
              <i class="icon_house_alt"></i>
              <span>Home</span>
            </a>
          </li>

          <li class="<%= params[:controller]== 'friendships' ? 'active' : '' %>">
            <a class="" href="<%=user_friendships_path(current_user.id) %>">
              <i class="icon_genius"></i>
              <span>Friends</span>
            </a>
          </li>

          <li class="<%= params[:controller]== 'groups' ? 'active' : '' %>">
            <a class="" href="<%=user_groups_path(current_user.id) %>">
              <i class="icon_piechart"></i>
              <span>Groups</span>
            </a>
          </li>
          <li onClick='reforders()' class="<%= params[:controller]== 'orders' ? 'active' : '' %>">
            <a class="" href="<%=orders_path %>">
              <i class="icon_documents_alt"></i>  
              <span>Orders</span>
            </a>
          </li>
         <% end %>
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->

    <!--main content start-->
    <section id="main-content">

      <section class="wrapper">
        <!-- page start-->
        <div class="row" style="margin-left:20px;margin-right:20px;">
      <%= yield %>

    </div>
  </section>
    </section>
    <!--main content end-->
  </section>



 



<!-- javascripts -->
    <!-- nice scroll -->
    <script src="/template/js/jquery.scrollTo.min.js"></script>
    <script src="/template/js/jquery.nicescroll.js" type="text/javascript"></script>
    <!--script for this page only-->
  <script src="/template/js/jquery.rateit.min.js"></script>
    <!-- custom select -->
    <script src="/template/js/jquery.customSelect.min.js" ></script>

   
    <!--custome script for all page-->
    <script src="/template/js/scripts.js"></script>
    <!-- custom script for this page-->
  <script src="/template/js/jquery.autosize.min.js"></script>
  <script src="/template/js/jquery.placeholder.min.js"></script>
  <script src="/template/js/gdp-data.js"></script>  
  <script src="/template/js/morris.min.js"></script>
  <script src="/template/js/sparklines.js"></script>
  <script src="/template/js/jquery.slimscroll.min.js"></script> 

<script type="text/javascript">

$("#groups").multiselect({

    noneSelectedText: "Select groups to invite",
}).multiselectfilter();
$("#friends").multiselect({

        noneSelectedText: "Select friends to invite",

}).multiselectfilter();
$("#order_for").multiselect({
    multiple: false,
    header: "Select an option",
    noneSelectedText: "Select an Option",
    selectedList: 1
  });

function refreshPage(){
    // window.location.reload();
   // location.reload();
    window.location = "/notifications" ;
} 
function refhome(){
    // window.location.reload();
   // location.reload();
    window.location = "/" ;
} 

function reforders(){
    // window.location.reload();
   // location.reload();
    window.location = "/orders" ;
} 

// $(".flickr_pagination a").onClick(window.location.reload());


</script>

</body>
</html>